@echo off
echo Testing Docker deployment...

echo Building Docker images...
docker-compose build

echo Starting Docker containers...
docker-compose up -d

echo Waiting for services to start...
echo Waiting 30 seconds for services to initialize...
timeout /t 30

echo Testing API health endpoint...
curl http://localhost:3001/api/health

echo.
echo Testing frontend...
start http://localhost:3000

echo.
echo Docker deployment test complete.
echo Press any key to stop the containers...
pause

echo Stopping Docker containers...
docker-compose down